version: '3'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
  frontend:
    build: ./client
    ports:
      - "5173:4173"
    env_file:
      - ./client/.env