name: Dockerized CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend Docker image
      - name: Build Backend Docker Image
        run: |
          docker buildx build \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --build-arg SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            --build-arg PORT=${{ secrets.PORT }} \
            --build-arg MONGODB_URL=${{ secrets.MONGODB_URL }} \
            --build-arg CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
            --build-arg CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
            --build-arg CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
            --build-arg STABILITY_API_KEY=${{ secrets.STABILITY_API_KEY }} \
            --build-arg COHERE_API_KEY=${{ secrets.COHERE_API_KEY }} \
            -t ${{ secrets.DOCKER_USERNAME }}/gyaani-backend:latest \
            --load \
            ./server

      - name: Push Backend Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gyaani-backend:latest

      # Build and push frontend Docker image
      - name: Build Frontend Docker Image
        run: |
          docker buildx build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/gyaani-frontend:latest \
            --load \
            ./client

      - name: Push Frontend Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gyaani-frontend:latest